# Generated by Django 3.1.4 on 2021-02-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210209_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
