# Generated by Django 3.1.4 on 2021-03-25 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_auto_20210313_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mapping_project', to='application.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mapping_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
